<?php 
try {
    $Forum = new Application_Model_Forum();
?>

<?php 

if(isset($this->Categories)){
   
?>
        
<?php foreach ($this->Categories as $key=>$value){  

            
            $ForumCategory = $Forum->getMainForumsByCategoryId($value['id']);
            
            
            if(!empty($ForumCategory)){
                
                ?>
                    <table border="1"> 
                    <tr><th> <?php echo $value['name']; ?> </th></tr>
                <?php
                foreach ($ForumCategory as $Forumkey=>$Forumvalue){
?>
                    <tr>
                        <td> 
                           
                            <b><a href="<?php echo $Forumvalue['id'];?>"><?php echo $Forumvalue['name'];?></a></b>
                            
                            
                            <?php
                            $SubForum =$Forum->getSubForumsById($Forumvalue['id']);
                            if(!empty($SubForum)){
                                foreach ($SubForum as $SubForumkey=>$SubForumvalue){
                                   ?>
                                     <a href="<?php echo $SubForumvalue['id'];?>"><?php echo $SubForumvalue['name'];?></a>   
                                    <?php
                                    
                                }
                            }
                            ?>
                            
                        </td>
                    </tr>
                  
            <?php       }  ?></table> <?php   }

      } ?>
   
    
  <?php  
}}  catch (Exception $exp){
         
        header("Location:".$this->baseUrl()."/Error/pagenotvalid/");
        die();
         
     }

?>