<?php 
try {
    $Forum = new Application_Model_Forum();
?>

<?php 

if(isset($this->Categories)){
   
?>
        
<?php foreach ($this->Categories as $key=>$value){  

            
            $ForumCategory = $Forum->getMainForumsByCategoryId($value['id']);
            
            
            if(!empty($ForumCategory)){
                
                ?>
                    <table border="1"> 
                    <tr><th> <?php echo $value['name']; ?> </th></tr>
                <?php
                foreach ($ForumCategory as $Forumkey=>$Forumvalue){
?>
                    <tr>
                        <td> 
                           
                            <b><a href="<?php echo $this->baseUrl()?>/Forum/index/id/<?php echo $Forumvalue['id'];?>"><?php echo $Forumvalue['name'];?></a></b>
                         </td>
                         <td> lol</td>
                    </tr>    
                            
                            <?php
                            $SubForum =$Forum->getSubForumsById($Forumvalue['id']);
                            if(!empty($SubForum)){
                                foreach ($SubForum as $SubForumkey=>$SubForumvalue){
                                   ?>
                                            <tr>
                                            <td> 
                                    &nbsp;&nbsp; <a href="<?php echo $this->baseUrl()?>/Forum/index/id/<?php echo $SubForumvalue['id'];?>"><?php echo $SubForumvalue['name'];?></a>   
                                    
                                           </td>
                                           <td> lol</td>
                                           </tr> 
                                    <?php
                                    
                                }
                            }
                            ?>
                            
                       
                  
            <?php       }  ?></table> <?php   }

      } ?>
   
    
  <?php  
}}  catch (Exception $exp){
         
        header("Location:".$this->baseUrl()."/Error/pagenotvalid/");
        die();
         
     }

?>