<?php 
try {    
    $user = new Application_Model_User();
    $userType = new Application_Model_UserType();

    $ckeditor = $this->baseUrl()."/ckeditor/ckeditor.js";
    echo $ckeditor;
    ?>


<script src= "<?php echo $ckeditor; ?>"></script>

<?php 
if(!isset($this->Post)){  header("Location:".$this->baseUrl()."/Error/pagenotvalid/"); die(); }
?>


<a href="<?php echo $this->baseUrl()?>/Index/">YumYum</a>    
<?php
    if(isset($this->myForum)){
    ?>
        <a href="<?php echo $this->baseUrl()?>/Forum/index/id/<?php echo $this->myForum['id'];?>"><?php echo $this->myForum['name'];?></a>    
        <br/>
<?php } ?>

        
<?php
    if(isset($this->myForumParent)){
    ?>
        <a href="<?php echo $this->baseUrl()?>/Forum/index/id/<?php echo $this->myForumParent['id'];?>"><?php echo $this->myForumParent['name'];?></a>    
        <br/>
<?php } ?>

        
        
<h> <?php echo $this->Post['title']; ?></h>
<br>


<table border="1">
            <tr><td>
                    <div> 
                    <?php 
                          $user_data = $user->getUserById($this->Post['user_id']);
                          $user_pp = $this->baseUrl() . "/images/users/".$user_data['profileimage'];                          
                          $myUserType = $userType->getUserTypeById($user_data['id'])[0]['type'];
                    ?>
                        <image src="<?php echo $user_pp; ?>" height="59" width="59" />
                        <br/>
                        <a href="<?php echo $this->baseUrl()?>/User/index/id/<?php echo $user_data['id'];?>"><?php echo $user_data['username'];?></a>    
                        <br/>
                       <?php echo $myUserType; ?>
                    </div> 
                    
                    </br>
                    
                    <div>
                    <?php
                            echo $this->Post['title'];
                            echo "<br/>";
                            echo $this->Post['body']; 
                            echo "<br/>";echo "<br/>";
                            echo $user_data['signature'];
                    ?> 
                    </div>
            </td></tr>
<?php 

if(isset($this->SubPosts)){
    
    foreach ($this->SubPosts as $key=>$value){
        ?>
            <tr><td>
                    <div> 
                    <?php 
                          $user_data = $user->getUserById($value['user_id']);
                          $user_pp = $this->baseUrl() . "/images/users/".$user_data['profileimage'];                          
                          $myUserType = $userType->getUserTypeById($user_data['id'])[0]['type'];
                    ?>
                        <image src="<?php echo $user_pp; ?>" height="59" width="59" />
                        <br/>
                        <a href="<?php echo $this->baseUrl()?>/User/index/id/<?php echo $user_data['id'];?>"><?php echo $user_data['username'];?></a>    
                        <br/>
                       <?php echo $myUserType; ?>
                    </div> 
                    
                    </br>
                    
                    <div>
                    <?php
                            
                            echo "<br/>";
                            echo $value['body'];
                            echo "<br/>";echo "<br/>";
                            echo $user_data['signature'];
                    ?> 
                    </div>
            </td></tr>
            
         <?php   
        
       

    }

}

    if($this->Post["locked"]=="0") {
    ?>


            <tr><td>
     <?php       
            $auth = Zend_Auth::getInstance();
            $user_info = $auth->getIdentity();
            //$user_info->id = "1";
            if ($user_info) {

                ?>
                    <script>
                    
                    function addComment(){
                        alert(CKEDITOR.instances.editor1.getData());
                        
                    }
                    </script>
                    
                    
                    
             
                    
                    
                    
                    
                <textarea class="ckeditor" name="editor1" id="editor1" ></textarea>
                
                <br/>
                <button onclick="addComment()">Comment</button>
                <?php
                
            }else{Properties
                ?>
                <form action="<?php echo $this->baseUrl()?>/user/login/" method="post">
                <input type="submit" value="Login to comment"/>
                </form>

                 <?php
            }
    ?>
    </td></tr>       
    <?php   
    } 



            
            

?>

            

</table>

     <?php }  catch (Exception $exp){
         
        header("Location:".$this->baseUrl()."/Error/pagenotvalid/");
        die();
         
     }?>
