<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>profilepage</b></p>
</div>

<?php
    echo '<h3>'.$this->userData['username'].'</h3></br>';
    echo '<font color="blue"> First Name: </font>'.$this->userData['firstname'].'</br>';
    echo '<font color="blue"> Last Name: </font>'.$this->userData['lastname'].'</br>';
    echo '<font color="blue"> Email: </font>'.$this->userData['email'].'</br>';
    echo '<font color="blue"> Date of Birth: </font>'.$this->userData['birth_date'].'</br>';
    
?>